// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tram_Schedule.DAL;

namespace Tram_Schedule.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211012122259_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Tram_Schedule.Models.Route", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("TramRoutes");
                });

            modelBuilder.Entity("Tram_Schedule.Models.Tram", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Trams");
                });

            modelBuilder.Entity("Tram_Schedule.Models.TramStop", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RouteID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RouteID");

                    b.ToTable("TramStops");
                });

            modelBuilder.Entity("Tram_Schedule.Models.TramStop", b =>
                {
                    b.HasOne("Tram_Schedule.Models.Route", null)
                        .WithMany("StopsList")
                        .HasForeignKey("RouteID");
                });

            modelBuilder.Entity("Tram_Schedule.Models.Route", b =>
                {
                    b.Navigation("StopsList");
                });
#pragma warning restore 612, 618
        }
    }
}
